Create Fibonachi.java
nikitoshom/JavaSummer2017 pull request #4
Opened 2017-07-02 09:05 UTC by nikitoshom

2017-07-02 09:10 UTC, AlexanderSoroka requested changes

2017-07-02 09:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +    int number_int = Integer.parseInt(string);
codestyle violation

2017-07-02 09:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +      System.out.println("It's number of sequence Febonachi");
return from method here and drop off else block in that case

2017-07-02 09:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +      if (number_int < 0) {
You cannot do it as user explicitly said he want to check negative number. He doesn't want to check |negative number|

2017-07-03 21:04 UTC, AlexanderSoroka requested changes

2017-07-03 21:04 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public int number_int;
why public? naming convention violation

2017-07-03 21:04 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public boolean TestFibonachi() {
pleas add blank line before method name

2017-07-04 14:08 UTC, AlexanderSoroka requested changes

2017-07-04 14:08 UTC, AlexanderSoroka commented on Fibonachi.java
> +    int number_int = Integer.parseInt(stringWithNumber);
again, naming convention violation. Please fix it to proceed with the review.

2017-07-04 14:20 UTC, nikitoshom commented on Fibonachi.java
> +    int number_int = Integer.parseInt(stringWithNumber);
Please, help. I don't understand about what kind of error is it? In which line?

2017-07-04 15:18 UTC, AlexanderSoroka requested changes

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public int InputNumber() {
javadoc missed

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +    String stringWithNumber = number.next();
why not nextInt()?

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +      resultOfTest = true;
avoid using any flags, just return true here

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +    int firstNumber = 1;
declare variable as close to first usage as possible

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +          resultOfTest = true;
return true;

2017-07-04 15:18 UTC, AlexanderSoroka commented on Fibonachi.java
> +    if (resultOfTest == true) {
if (result)

2017-07-07 05:10 UTC, AlexanderSoroka requested changes

2017-07-07 05:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public int InputNumber() {
javadoc comment missed, naming convention violation (codestyle 5.2.3)

2017-07-07 05:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public boolean TestFibonachi(int numberInt) {
javadoc comment missed, naming convention violation (codestyle 5.2.3)

2017-07-07 05:10 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public void OutputResult (Boolean resultOfTest) {
javadoc comment missed, naming convention violation (codestyle 5.2.3)

2017-07-07 10:28 UTC, AlexanderSoroka requested changes
Javadoc violations: neither arguments nor return value are described

2017-07-10 07:44 UTC, AlexanderSoroka requested changes

2017-07-10 07:44 UTC, AlexanderSoroka commented on Fibonachi.java
> +    } else {
Useless else (as you have return in "if" block)

2017-07-10 07:44 UTC, AlexanderSoroka commented on Fibonachi.java
> +  public void outputResult (Boolean resultOfTest) {
non-appropriate argument name

2017-07-10 07:44 UTC, AlexanderSoroka commented on Fibonachi.java
> +   * @param boolean result of previos method (testFibonachi()).
Who guarantees that previous method always is  testFibonachi?

2017-07-12 05:54 UTC, AlexanderSoroka approved these changes

2017-07-18 12:33 UTC, AlexanderSoroka approved these changes

2017-08-03 12:32 UTC, merged